In [76]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [131]:
actual = pd.read_csv('internship_train.csv')

In [78]:
pred = pd.read_csv('internship_hidden_test.csv')

In [85]:
X_train = actual.drop('target',axis = 1)
y_train = actual['target']


In [132]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
model = reg.fit(X_train,y_train)

In [145]:
y_predict =  reg.predict(pred)
y_predict

array([48.64961597, 51.23861561, 49.84939509, ..., 51.08310798,
       50.27217454, 50.8549678 ])

In [147]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_train,y_predict))

ValueError: Found input variables with inconsistent numbers of samples: [90000, 10000]

In [133]:
model.intercept_

49.282517019512845

In [135]:
model.coef_

array([ 4.36061322e-04, -1.12481037e-03,  1.89191872e-04,  5.84160662e-04,
       -2.73840884e-04, -4.14562002e-04,  1.43715436e-02,  1.23082188e+00,
       -1.73138228e-01,  3.16932074e-04,  6.80974576e-04, -3.31550868e-04,
        3.85163941e-04, -6.91027734e-03, -4.62518343e-03,  1.16632641e-02,
       -5.26778932e-03,  1.94944891e-02,  7.02452895e-03,  9.96024389e-03,
       -3.49452821e-03,  1.93446686e-02,  1.36760817e-03,  8.60322443e-03,
        7.55314813e-03,  2.92681578e-02,  4.31263919e-02, -9.99962415e-03,
        2.31601422e-02, -3.16334842e-02, -5.86887887e-03,  3.30948570e-02,
        4.48214627e-03, -1.41444787e-02,  8.34719240e-03, -4.21754807e-02,
        1.73499711e-02,  1.12897162e-02, -2.55620494e-02,  4.30455067e-02,
       -4.93424066e-02, -2.63404640e-02, -1.96349737e-02,  3.02168721e-03,
        2.11365186e-02, -5.69593703e-03,  8.28709875e-03,  1.44550241e-03,
       -7.01976832e-03,  1.55593759e-02, -3.53878772e-02, -3.13070084e-02,
       -7.95561505e-03])

In [136]:
X_train,y_train

(         0    1    2    3    4    5         6         7  8    9  ...  \
 0      236  488   16  221  382   97 -4.472136  0.107472  0  132  ...   
 1      386  206  357  232    1  198  7.810250  0.763713  1  143  ...   
 2      429   49  481  111  111  146  8.602325  0.651162  1  430  ...   
 3      414  350  481  370  208  158  8.306624  0.424645  1  340  ...   
 4      318  359   20  218  317  301  8.124038  0.767304  1  212  ...   
 ...    ...  ...  ...  ...  ...  ...       ...       ... ..  ...  ...   
 89995  328   44  320  364    7   73  4.898979  0.563878  1  315  ...   
 89996  217  472  174  327  255  389 -3.605551  0.861690  0  144  ...   
 89997  189  406  213   57  494  190  6.164414  0.633704  1  221  ...   
 89998  418  478  163   35  390   77 -3.605551  0.687309  0  289  ...   
 89999  244  335  337  152  386  202  7.681146  0.613207  1   26  ...   
 
               43         44        45         46         47         48  \
 0      10.125020  13.340874  0.870542   1.9629

In [137]:
y_pred = 75*model.coef_ + model.intercept_
y_pred

array([ 49.31522162,  49.19815624,  49.29670641,  49.32632907,
        49.26197895,  49.25142487,  50.36038279, 141.5941579 ,
        36.29714991,  49.30628693,  49.33359011,  49.2576507 ,
        49.31140432,  48.76424622,  48.93562826,  50.15726183,
        48.88743282,  50.7446037 ,  49.80935669,  50.02953531,
        49.0204274 ,  50.73336717,  49.38508763,  49.92775885,
        49.84900313,  51.47762885,  52.51699641,  48.53254521,
        51.01952768,  46.9100057 ,  48.8423511 ,  51.76463129,
        49.61867799,  48.22168112,  49.90855645,  46.11935597,
        50.58376485,  50.12924574,  47.36536332,  52.51093002,
        45.58183652,  47.30698222,  47.80989399,  49.50914356,
        50.86775591,  48.85532174,  49.90404943,  49.3909297 ,
        48.7560344 ,  50.44947021,  46.62842623,  46.93449139,
        48.68584589])

In [138]:
y_pred = X_train*model.coef_ + model.intercept_
y_pred

0          1          2          3          4          5  \
0      49.385427  48.733610  49.285544  49.411617  49.177910  49.242305   
1      49.450837  49.050806  49.350059  49.418042  49.282243  49.200434   
2      49.469587  49.227401  49.373518  49.347359  49.252121  49.221991   
3      49.463046  48.888833  49.373518  49.498656  49.225558  49.217016   
4      49.421185  48.878710  49.286301  49.409864  49.195709  49.157734   
...          ...        ...        ...        ...        ...        ...   
89995  49.425545  49.233025  49.343058  49.495152  49.280600  49.252254   
89996  49.377142  48.751607  49.315436  49.473538  49.212688  49.121252   
89997  49.364933  48.825844  49.322815  49.315814  49.147240  49.203750   
89998  49.464791  48.744858  49.313355  49.302963  49.175719  49.250596   
89999  49.388916  48.905706  49.346275  49.371309  49.176814  49.198775   

               6          7          8          9  ...         43         44  \
0      49.218246  49.414796  49.282517  49.324352  ...  49.313112  49.564497   
1      49.394762  50.222512  49.109379  49.327838  ...  49.314501  49.546404   
2      49.406146  50.083981  49.109379  49.418798  ...  49.313559  49.579068   
3      49.401896  49.805180  49.109379  49.390274  ...  49.303322  49.341479   
4      49.399272  50.226931  49.109379  49.349707  ...  49.316247  49.322392   
...          ...        ...        ...        ...  ...        ...        ...   
89995  49.352923  49.976550  49.109379  49.382351  ...  49.298387  49.288147   
89996  49.230700  50.343104  49.282517  49.328155  ...  49.327047  49.391308   
89997  49.371109  50.062494  49.109379  49.352559  ...  49.304564  49.597510   
89998  49.230700  50.128471  49.282517  49.374110  ...  49.324651  49.551860   
89999  49.392907  50.037266  49.109379  49.290757  ...  49.286110  49.516479   

              45         46         47         48         49         50  \
0      49.277558  49.298784  49.293310  49.201454  49.419796  48.962383   
1      49.241685  49.306429  49.300461  49.210491  49.439532  48.954440   
2      49.280267  49.350145  49.300719  49.219777  49.317762  48.884201   
3      49.245968  49.369944  49.299077  49.237112  49.321712  49.273377   
4      49.271581  49.301314  49.282733  49.253695  49.444588  49.041306   
...          ...        ...        ...        ...        ...        ...   
89995  49.247283  49.346467  49.297181  49.270502  49.342416  48.843640   
89996  49.258539  49.402537  49.284505  49.237687  49.439785  48.835289   
89997  49.266076  49.354475  49.289054  49.271591  49.453222  49.006767   
89998  49.268131  49.374091  49.292043  49.193912  49.447397  49.259600   
89999  49.246613  49.398797  49.285231  49.188722  49.316198  48.884220   

              51         52  
0      49.035331  49.194920  
1      49.183149  49.171760  
2      48.881949  49.186406  
3      48.990808  49.239691  
4      49.013685  49.246618  
...          ...        ...  
89995  48.838097  49.263653  
89996  49.076632  49.227916  
89997  49.018830  49.258321  
89998  49.008695  49.272599  
89999  49.175938  49.206244  

[90000 rows x 53 columns]

In [148]:
y_pred = model.predict(pred)
y_pred

array([48.64961597, 51.23861561, 49.84939509, ..., 51.08310798,
       50.27217454, 50.8549678 ])

In [139]:
y_pred = model.predict(X_train)
y_pred

array([50.07030081, 50.82482827, 50.62416539, ..., 50.49428441,
       51.37982244, 50.31660035])

In [140]:
model.score(X_train,y_train)

0.000631210379404723

In [141]:
model.coef_

array([ 4.36061322e-04, -1.12481037e-03,  1.89191872e-04,  5.84160662e-04,
       -2.73840884e-04, -4.14562002e-04,  1.43715436e-02,  1.23082188e+00,
       -1.73138228e-01,  3.16932074e-04,  6.80974576e-04, -3.31550868e-04,
        3.85163941e-04, -6.91027734e-03, -4.62518343e-03,  1.16632641e-02,
       -5.26778932e-03,  1.94944891e-02,  7.02452895e-03,  9.96024389e-03,
       -3.49452821e-03,  1.93446686e-02,  1.36760817e-03,  8.60322443e-03,
        7.55314813e-03,  2.92681578e-02,  4.31263919e-02, -9.99962415e-03,
        2.31601422e-02, -3.16334842e-02, -5.86887887e-03,  3.30948570e-02,
        4.48214627e-03, -1.41444787e-02,  8.34719240e-03, -4.21754807e-02,
        1.73499711e-02,  1.12897162e-02, -2.55620494e-02,  4.30455067e-02,
       -4.93424066e-02, -2.63404640e-02, -1.96349737e-02,  3.02168721e-03,
        2.11365186e-02, -5.69593703e-03,  8.28709875e-03,  1.44550241e-03,
       -7.01976832e-03,  1.55593759e-02, -3.53878772e-02, -3.13070084e-02,
       -7.95561505e-03])

In [142]:
import math
r = math.sqrt(0.000631210379404723)
r

0.025123900561113577

In [143]:
actual.corr()

0         1         2         3         4         5         6  \
0       1.000000  0.002009  0.001170  0.002957 -0.003764 -0.007362  0.007855   
1       0.002009  1.000000 -0.001849 -0.004653 -0.002433 -0.002037  0.004181   
2       0.001170 -0.001849  1.000000 -0.000775  0.003082 -0.002161  0.002296   
3       0.002957 -0.004653 -0.000775  1.000000 -0.003623 -0.001038  0.000223   
4      -0.003764 -0.002433  0.003082 -0.003623  1.000000 -0.000992  0.005602   
5      -0.007362 -0.002037 -0.002161 -0.001038 -0.000992  1.000000 -0.003869   
6       0.007855  0.004181  0.002296  0.000223  0.005602 -0.003869  1.000000   
7       0.007174  0.005790 -0.000299 -0.004290 -0.004459 -0.001455 -0.002051   
8       0.008011  0.004095  0.001983  0.000966  0.004763 -0.002289  0.940016   
9       0.002339  0.002592  0.005753  0.000202 -0.000778  0.004740 -0.007185   
10      0.000066 -0.002682 -0.002199 -0.004965 -0.000388 -0.003559  0.001613   
11     -0.001815 -0.000078  0.000317 -0.000367  0.001954  0.000507 -0.000223   
12      0.000896  0.001109  0.005324  0.000916 -0.001668 -0.000037 -0.002390   
13     -0.000404 -0.004103  0.002116  0.000080 -0.000544 -0.002532 -0.003157   
14     -0.000075 -0.001656  0.008375  0.003102  0.002047  0.000901 -0.005814   
15     -0.000253 -0.000614  0.003951  0.001020  0.000488 -0.001526 -0.000298   
16      0.002622  0.002029 -0.001875 -0.007037  0.001208  0.001329 -0.004747   
17      0.006260  0.002349 -0.000639 -0.005790  0.001100  0.000324 -0.000960   
18      0.000741  0.001863  0.001350  0.007506 -0.001374  0.000658 -0.000464   
19      0.002210  0.000461 -0.000633  0.001275 -0.000336 -0.002281  0.003840   
20     -0.000895  0.000178 -0.000888 -0.002047  0.002304 -0.000124  0.006525   
21     -0.007855 -0.001536 -0.001534  0.000044  0.001397  0.000868 -0.002993   
22     -0.002258 -0.003732 -0.000585  0.004518  0.002999 -0.001166  0.000800   
23      0.004361  0.003922  0.002231  0.001132  0.001657  0.002663  0.003302   
24      0.002187 -0.004662  0.000821  0.002010 -0.008401  0.005036 -0.001978   
25     -0.004042  0.003783  0.000266 -0.006407 -0.002119  0.004169 -0.002176   
26      0.005097 -0.003006 -0.005920  0.005319  0.006148  0.005809 -0.003016   
27     -0.003047 -0.001918  0.002083 -0.003369 -0.002811 -0.000554  0.002847   
28      0.002541 -0.002799  0.002801 -0.002658  0.000857 -0.004874 -0.002015   
29     -0.001587 -0.004662 -0.004899 -0.002173 -0.002049 -0.001341 -0.000106   
30     -0.000414  0.001058  0.001974  0.001568  0.000079 -0.000250  0.002109   
31      0.006611 -0.002409 -0.002710  0.001985  0.003268  0.003361  0.004690   
32     -0.002760  0.005470  0.004933  0.003247 -0.005772  0.006335  0.006170   
33      0.000027  0.010357 -0.002065 -0.003471  0.001476  0.000679 -0.005689   
34      0.008256 -0.002004  0.005319  0.001715  0.001039 -0.005939 -0.006711   
35     -0.004086 -0.005055 -0.000625 -0.001856 -0.000371  0.005656 -0.003161   
36     -0.004529 -0.000449  0.001144  0.001179 -0.006524 -0.000340 -0.003249   
37      0.003246 -0.003830  0.003342 -0.004269  0.000780  0.000682  0.000200   
38      0.000787  0.002414 -0.001261 -0.003873 -0.005631  0.000071  0.001246   
39      0.000185  0.006489  0.002653 -0.004087  0.002509  0.000860  0.000057   
40     -0.002930 -0.000481 -0.002015  0.007568 -0.008978  0.004089 -0.000819   
41      0.003764 -0.002569  0.002044  0.004309  0.004317  0.003336  0.002212   
42     -0.000167  0.007752 -0.002604  0.000720 -0.000019 -0.000008 -0.003423   
43      0.001234 -0.002425 -0.001275  0.000752 -0.009656 -0.008769  0.004318   
44     -0.004142 -0.002875  0.001092 -0.005876 -0.001413 -0.001160  0.000580   
45     -0.006525 -0.002679 -0.000588  0.004777  0.006178 -0.005226 -0.000033   
46      0.003532  0.001402  0.000643  0.001334 -0.000873 -0.000776  0.005084   
47      0.000310 -0.007900  0.003106  0.000528 -0.002625 -0.000087 -0.002972   
48     -0.002639 -0.004497  0.001611  0.006892 -0.001883 -0.004682 -0.002300   
49      0.00479