In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [3]:
actual = pd.read_csv('internship_train.csv')
pred = pd.read_csv('internship_hidden_test.csv')

In [36]:
actual.isnull().sum()
pred.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
48    0
49    0
50    0
51    0
52    0
dtype: int64

In [33]:
X_train = actual.drop('target',axis = 1)
y_train = actual['target']


In [5]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [6]:
model = lr.fit(X_train,y_train) #training the model

In [7]:
c = model.intercept_

In [8]:
c

49.282517019512845

In [9]:
n = model.coef_
n

array([ 4.36061322e-04, -1.12481037e-03,  1.89191872e-04,  5.84160662e-04,
       -2.73840884e-04, -4.14562002e-04,  1.43715436e-02,  1.23082188e+00,
       -1.73138228e-01,  3.16932074e-04,  6.80974576e-04, -3.31550868e-04,
        3.85163941e-04, -6.91027734e-03, -4.62518343e-03,  1.16632641e-02,
       -5.26778932e-03,  1.94944891e-02,  7.02452895e-03,  9.96024389e-03,
       -3.49452821e-03,  1.93446686e-02,  1.36760817e-03,  8.60322443e-03,
        7.55314813e-03,  2.92681578e-02,  4.31263919e-02, -9.99962415e-03,
        2.31601422e-02, -3.16334842e-02, -5.86887887e-03,  3.30948570e-02,
        4.48214627e-03, -1.41444787e-02,  8.34719240e-03, -4.21754807e-02,
        1.73499711e-02,  1.12897162e-02, -2.55620494e-02,  4.30455067e-02,
       -4.93424066e-02, -2.63404640e-02, -1.96349737e-02,  3.02168721e-03,
        2.11365186e-02, -5.69593703e-03,  8.28709875e-03,  1.44550241e-03,
       -7.01976832e-03,  1.55593759e-02, -3.53878772e-02, -3.13070084e-02,
       -7.95561505e-03])

In [31]:
# Test the model
y_pred_train = lr.predict(X_train)
y_pred_train
print('The model score is:',  model.score(X_train,y_train))

The model score is: 0.000631210379404723


In [19]:
#Make the predictions
y_pred_test = lr.predict(pred)
y_pred_test

array([48.64961597, 51.23861561, 49.84939509, ..., 51.08310798,
       50.27217454, 50.8549678 ])

In [15]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_train,y_pred_train))
rmse

28.887960642821337

In [ ]:
# RandomForestRegretion

In [16]:
from sklearn.ensemble import RandomForestRegressor
model_2 = RandomForestRegressor()
model_2.fit(X_train,y_train) #training the model

RandomForestRegressor()

In [26]:
# Test the model
predictions = model_2.predict(X_train)
predictions
print('The model score is:',  model_2.score(X_train,y_train))




The model score is: 0.9999999982957564


In [30]:
# Make the predictions
prediction = model_2.predict(pred)
prediction



array([11.21726257, 79.70192307,  7.49467933, ..., 22.82639883,
       16.50291746, 91.98592   ])

In [32]:
rmse = np.sqrt(mean_squared_error(y_train,predictions))
rmse

0.0011929433695662599